version: '3.8'
services:
  nginx:
    image: "${FRONT_IMAGE_NAME}:${BUILD_NUMBER}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /home/dudtjr20027/default.conf:/etc/nginx/conf.d/default.conf:ro
  backend:
    image: ${BACK_IMAGE_NAME}:${BUILD_NUMBER}
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://34.47.92.146:3306/ssafy
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "!A123456b"
    ports:
      - "8000:8000"

