version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/dudtjr20027/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/temp206.duckdns.org/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/temp206.duckdns.org/privkey.pem:/etc/ssl/private/privkey.pem:ro
