version: '3.8'
services:
  nginx:
    image: "${FRONT_IMAGE_NAME}:${BUILD_NUMBER}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /home/dudtjr20027/default.conf:/etc/nginx/conf.d/default.conf:ro
  backend:
    image: ${BACK_IMAGE_NAME}:${BUILD_NUMBER}
    ports:
      - "8000:8000"

