services:
  frontend:
    image: ${FRONT_IMAGE_NAME}:${BUILD_NUMBER}
    ports:
      - "3000:3000"
    volumes:
      - /usr/share/nginx/html/build:/build
    backend:
        image: ${BACK_IMAGE_NAME}:${BUILD_NUMBER}
        ports:
            - "8000:8000"
        depends_on:
            - frontend
