spring:
  config:
    import: classpath:env.yml
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 100

  profiles:
    active: local
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

logging:
  level:
    org.hibernate.SQL: trace
    org.springframework.security: debug
    org.ssafy.studyback: DEBUG