spring:
  config:
    import: optional:classpath:env.yml
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 100
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbblkjlkjkldfdhgfhjgkjb

  h2:
    console:
      enabled: false

  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:gcs_cloud.json
        project-id: compelling-weft-415104
        bucket: d206

  profiles:
    active: local
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

logging:
  level:
    org.hibernate.SQL: trace
    org.springframework.security: debug
    org.ssafy.studyback: DEBUG

server:
  port: 8000

cors:
  allowed-origins: http://localhost:3000

