spring:
  datasource:
    url: jdbc:mysql://34.47.92.146:3306/ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "!A123456bc"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 100
  profiles:
    active: local
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

logging:
  level:
    org.hibernate.SQL: trace
    org.springframework.security: debug
    org.ssafy.studyback: DEBUG