spring:
#  원격 db
 datasource:
   url: jdbc:mysql://34.64.150.109:3306/ssafy?serverTimezone=UTC&characterEncoding=UTF-8
   driver-class-name: com.mysql.cj.jdbc.Driver
   username: root
   password: "!A123456bc"


 jpa:
  database: mysql
  database-platform: org.hibernate.dialect.MySQL8Dialect # 추가 해준 부분 추가 해준 부분
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      show_sql: false
      format_sql: true
      default_batch_fetch_size: 100
 profiles:
  active: local
 servlet:
  multipart:
    max-request-size: 30MB
    max-file-size: 10MB

logging:
  level:
    org.hibernate.SQL: trace
    org.springframework.security: debug
    org.ssafy.studyback: DEBUG
